"""empty message

Revision ID: 4b02582eae14
Revises: 5e1c8c84159c
Create Date: 2024-06-17 17:45:46.202071

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")



# revision identifiers, used by Alembic.
revision = '4b02582eae14'
down_revision = '5e1c8c84159c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=250), nullable=False),
    sa.Column('street_address', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('tokenId', sa.Integer(), nullable=False),
    sa.Column('isNorthAmerica', sa.Boolean(create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('street_address'),
    sa.UniqueConstraint('tokenId')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tokenDna', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tokenDna')
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE shipping_forms SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE tokens SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('shipping_forms')
    # ### end Alembic commands ###
