"""empty message

Revision ID: 5e1c8c84159c
Revises: 616d6aa7b99f
Create Date: 2024-02-23 23:58:55.124370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1c8c84159c'
down_revision = '616d6aa7b99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.alter_column('wallet_address',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.alter_column('wallet_address',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
